# Generated by Django 5.1.3 on 2024-12-04 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.car'),
            preserve_default=False,
        ),
    ]
